### ISSUE TITLE
README.md "Major League Hacking" Hyperlink is Not Found

### ISSUE THREAD

**Issue by sbaljeet13** [MLH/mlh-hackathon-nodejs-starter#4]
The link for 

> ...created by [Major League Hacking](https://github.com/jekyll/jekyll/blob/master/CONDUCT.markdown).

in [README.md](https://github.com/MLH/mlh-hackathon-nodejs-starter/blob/master/README.md) is redirecting to a broken link of **jekyll** project.

Possibly should be redirecting to https://github.com/MLH similar to the one in https://github.com/MLH/mlh-hackathon-flask-starter/blob/master/README.md

**Comment by iFlameing** [comment]
I would like to work on this issue :) should I have to add this link or something else https://github.com/MLH/mlh-hackathon-flask-starter/blob/master/README.md

**Comment by nlaz** [comment]
@sbaljeet13 good catch! Thanks for reporting it.

@iFlameing if you would like to work on it, you are welcome to open a PR with the fix.

**Comment by sbaljeet13** [comment]
@iFlameing [Major League Hacking](https://github.com/MLH) should be redirecting to https://github.com/MLH in my opinion.

No problem, @nlaz. Glad to have this kickstarter project ✈️
