### ISSUE TITLE
Application Error with Demo Link 

### ISSUE THREAD

**Issue by nguyen-nhat** [MLH/mlh-hackathon-nodejs-starter#9]
https://hackathon-starter-nodejs.herokuapp.com/

Error Message:
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
`heroku logs --tail`

![](https://i.imgur.com/0cFW8YP.png)

**Comment by nlaz** [comment]
Thanks for catching the issue with the demos. It should be running again!
